sudo: false
os: linux
language: go

go:
  - 1.12

before_install:
  - env GO111MODULE=on go get ./...
  - env GO111MODULE=off go get github.com/alecthomas/gometalinter

install:
  - GO111MODULE=off gometalinter --install --force

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - echo $TRAVIS_BRANCH

script:
  - go vet ./...
  - GO111MODULE=off gometalinter ./...
