version: "3"

volumes:
#  ft-mysql-data:
  sp-mongo-data:

services:
  sp-api:
    container_name: sp-api
    build:
      context: .
      dockerfile: .docker/golang/api/Dockerfile
    volumes:
      - .:/sp-event
    env_file:
      - ./.docker/golang/api/.env
    depends_on:
      - sp-mongo
    links:
      - sp-mongo

#  ft-mysql:
#    container_name: ft-mysql
#    image: ft-mysql
#    build:
#      context: .
#      dockerfile: .docker/mysql/Dockerfile
#    volumes:
#      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#      - ft-mysql-data:/var/lib/mysql
#    ports:
#      - 3309:3306
#    env_file:
#      - ./.docker/mysql/.env
#    networks:
#      - fintech-backend

  sp-mongo:
    container_name: sp-mongo
    build:
      context: .
      dockerfile: .docker/mongo/Dockerfile
    command: mongod --auth
    ports:
      - 27017:27017
    env_file:
      - ./.docker/mongo/.env
    volumes:
      - sp-mongo-data:/data/db
      - ./.docker/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
